### ISSUE TITLE
[ÖNERİ] Log dosyası ve response time & uptime...

### ISSUE THREAD

**Issue by cronus** [aligoren/CheckUp.go#2]
Logları bir log dosyasına response time ile birlikte yazdırılabilir.
Verilerden uptime yüzdesi hesaplanabilir.

Başarılar.

**Comment by aligoren** [comment]
@cronus Teşekkürler dostum bu Go scripti doğru bile çalışmıyor bence :) Ama evet bunu daha çok şöyle düşünüyorum. Bi tane web framework ya da standart kendi özellikleri ile tam zamanlı sonuç gösterimi yapabilirim. Chart falan kullanılır monitoring mantığı yani

**Comment by cronus** [comment]
https://git.io/vSm14 ❤️
